# Generated by Django 2.2.6 on 2020-08-06 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Admin', max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=240)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('content', models.TextField()),
                ('urlToImage', models.CharField(blank=True, max_length=2038, null=True)),
                ('urlToPost', models.CharField(blank=True, max_length=3000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
